export const GET_PICTURE_OF_THE_DAY = 'apod/GET_PICTURE_OF_THE_DAY';
export const GET_PICTURE_OF_THE_DAY_SUCCESS =
  'apod/GET_PICTURE_OF_THE_DAY_SUCCESS';
export const GET_PICTURE_OF_THE_DAY_FAILURE =
  'apod/GET_PICTURE_OF_THE_DAY_FAILURE';
